services:
  app:
    build: .
    container_name: amity-backend
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules
            - .git
            - .env
        - action: rebuild
          path: package.json

  mongodb:
    attach: false
    image: mongo:latest
    container_name: amity-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
